---
- name: APT. Update repository cache
  apt: 
    update_cache: yes
  tags:
    - done

- name: Readmine. Install packages
  apt:
    name: "{{ apt_redmine_packages }}"
    state: latest
  tags:
    - done

- name: MySQL. Install and setup
  block:
  - template: 
      src: .my.cnf 
      dest: ~/.my.cnf 
      owner: root 
      mode: 0600
  - service:
      name: mysql
      state: started
      enabled: yes
  tags:
    - done

- mysql_db: 
    name: "{{ app_db_name }}"
    encoding: utf8
  tags:
    - done

- mysql_user: 
    name: "{{ app_db_user }}"
    password: "{{ app_db_pass }}"
    priv: "{{ app_db_name }}.*:ALL"
  tags:
    - done


- name: Redmine. Clone repository
  git: 
    repo: "{{ app_repo }}" 
    dest: "{{ app_home }}" 
    version: '{{ app_version }}' 
    accept_hostkey: yes
  tags:
    - done

- name: "Redmine. Change permissions on {{ app_home }}/public"
  file:
    path: "{{ app_home }}/public"
    owner: www-data
    group: www-data
    recurse: yes
  tags:
    - done

- name: "Redmine. Change permissions on {{ app_home }}/tmp"
  file:
    path: "{{ app_home }}/tmp"
    mode: 777
    recurse: yes 
  tags:
    - done

- name: Config database
  template: 
    src: database.yml.j2 
    dest: "{{ app_home }}/config/database.yml"
  tags:
    - done

- name: Redmine. Setup 01
  shell: |
    gem install bundler
    bundle update   
  args:
    executable: /bin/bash
    chdir: "{{ app_home }}"
  tags:
    - done

- name: Session store secret generation
  shell: rake generate_secret_token
  args:
   chdir: "{{ app_home }}"
   creates: "{{ app_home }}/config/initializers/secret_token.rb"


- name: Redmine. Setup 02
  shell: | 
    bundle exec rake db:migrate RAILS_ENV=production 
    bundle exec rake redmine:plugins:migrate RAILS_ENV=production
    bundle install --without development test
    RAILS_ENV=production rake db:migrate
    RAILS_ENV=production REDMINE_LANG="{{ app_lang }}" rake redmine:load_default_data
    #bundle exec rails server webrick -e production
  args:
    chdir: "{{ app_home }}"
