---
apt_redmine:
  - git
  - ruby-full
  - build-essential 
  - libmysqlclient-dev 
  - imagemagick 
  - libmagickwand-dev
  - apache2 
  - libapache2-mod-passenger
  - mysql-server 
  - mysql-client
  - python-pymysql

app_db_name: redmine
app_db_user: redmine
app_db_pass: redmine