---
- name: Apt update
  apt:
    update_cache: yes
    
- name: Redmine. Install packages
  apt:
    name: "{{ apt_redmine }}"
    state: latest

- name: MySQL. Setup
  block:
  - template:
      src: templates/.my.cnf
      dest: ~/.my.cnf
      owner: root
      mode: 0600
    notify: 
      - mysql restart
- mysql_db:
    name: "{{ app_db_name }}"
    encoding: utf8

- mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_pass }}"
    priv: "{{ app_db_name }}.*:ALL"
